### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by diStyApps** [adrianpuiu/kandinsky#1]
Hello,
thank you for that script. I have added your UI script to my installation tool for Kandinsky installation. You can find the tool at https://github.com/diStyApps/seait
![Screenshot 2023-04-29 180657](https://user-images.githubusercontent.com/3084832/235310104-87b3709b-db91-41bf-99d0-5bfda4ebe91d.jpg)

**Comment by adrianpuiu** [comment]
youre very welcome mate, but you might wanna check this one out https://github.com/seruva19/kubin , hes done a far better job then mine 
@seruva19 are you ok with adding your wui to this install ? yours its much better

**Comment by seruva19** [comment]
Sure, no problem.

**Comment by diStyApps** [comment]
Thank you both of you very much awesome work i will test and add it.
